var coaches = [
    {
        "EnglishName": "Hillman",
        "JapaneseName": "Hibiki",
        "Gender": "Male",
        "Role": "Coach",
        "Position": "",
        "Element": "",
        "Sprite": "https://vignette.wikia.nocookie.net/inazuma-eleven/images/7/70/Hibiki_Seigou_coach_uniform.png",
        "EnglishTeam": "Raimon",
        "JapaneseTeam": "Raimon",
        "TeamSprite": "https://vignette.wikia.nocookie.net/inazuma-eleven/images/4/4a/Raimon_Logo_Sprite.png",
        "Game": "IE1"
    },
    {
        "EnglishName": "Jyde",
        "JapaneseName": "Jikiru",
        "Gender": "Male",
        "Role": "Coach",
        "Position": "",
        "Element": "",
        "Sprite": "https://vignette.wikia.nocookie.net/inazuma-eleven/images/0/01/Jikiru_Haito_alter_ego.png",
        "EnglishTeam": "Occult",
        "JapaneseTeam": "Occult",
        "TeamSprite": "https://vignette.wikia.nocookie.net/inazuma-eleven/images/d/dd/Occult_emblem.png",
        "Game": "IE1"
    },
    {
        "EnglishName": "Savage",
        "JapaneseName": "Tazan",
        "Gender": "Male",
        "Role": "Coach",
        "Position": "",
        "Element": "",
        "Sprite": "https://vignette.wikia.nocookie.net/inazuma-eleven/images/4/4f/Tazan.png",
        "EnglishTeam": "Wild",
        "JapaneseTeam": "Nose",
        "TeamSprite": "https://vignette.wikia.nocookie.net/inazuma-eleven/images/3/3c/Nosei_emblem.png",
        "Game": "IE1"
    },
    {
        "EnglishName": "Thomas",
        "JapaneseName": "Toyama",
        "Gender": "Male",
        "Role": "Coach",
        "Position": "",
        "Element": "",
        "Sprite": "https://vignette.wikia.nocookie.net/inazuma-eleven/images/b/b9/Toyama_Shinnichirou.png",
        "EnglishTeam": "Brainwashing",
        "JapaneseTeam": "Mikage Sennou",
        "TeamSprite": "https://vignette.wikia.nocookie.net/inazuma-eleven/images/6/69/Mikage_Sennou%27s_Emblem.png",
        "Game": "IE1"
    },
    {
        "EnglishName": "Artic",
        "JapaneseName": "Maniya",
        "Gender": "Male",
        "Role": "Coach",
        "Position": "",
        "Element": "",
        "Sprite": "https://vignette.wikia.nocookie.net/inazuma-eleven/images/2/29/Coach5shot.png",
        "EnglishTeam": "Otaku",
        "JapaneseTeam": "Shuuyou Meito",
        "TeamSprite": "https://vignette.wikia.nocookie.net/inazuma-eleven/images/f/fd/Shuuyou_Meito_Emblem.png",
        "Game": "IE1"
    },
    {
        "EnglishName": "Dark",
        "JapaneseName": "Kageyama",
        "Gender": "Male",
        "Role": "Coach",
        "Position": "",
        "Element": "",
        "Sprite": "https://vignette.wikia.nocookie.net/inazuma-eleven/images/3/37/Kageyamareijishot.png",
        "EnglishTeam": "Royal Academy",
        "JapaneseTeam": "Teikoku Gakuen",
        "TeamSprite": "https://vignette.wikia.nocookie.net/inazuma-eleven/images/b/b4/Teikoku_emblem_sprite.png",
        "Game": "IE1"
    },
    {
        "EnglishName": "Igajima",
        "JapaneseName": "Igajima",
        "Gender": "Male",
        "Role": "Coach",
        "Position": "",
        "Element": "",
        "Sprite": "https://vignette.wikia.nocookie.net/inazuma-eleven/images/3/34/Coach6shot.png",
        "EnglishTeam": "Shuriken",
        "JapaneseTeam": "Sengoku Igajima",
        "TeamSprite": "https://vignette.wikia.nocookie.net/inazuma-eleven/images/9/9c/Sengoku_Igajima_emblem.png",
        "Game": "IE1"
    },
    {
        "EnglishName": "Newfield",
        "JapaneseName": "Shinno",
        "Gender": "Male",
        "Role": "Coach",
        "Position": "",
        "Element": "",
        "Sprite": "https://vignette.wikia.nocookie.net/inazuma-eleven/images/2/2c/Coach7shot.png",
        "EnglishTeam": "Farm",
        "JapaneseTeam": "Senbayama",
        "TeamSprite": "https://vignette.wikia.nocookie.net/inazuma-eleven/images/1/16/Senbayama_Logo.png",
        "Game": "IE1"
    },
    {
        "EnglishName": "Nichols",
        "JapaneseName": "Nikaidou",
        "Gender": "Male",
        "Role": "Coach",
        "Position": "",
        "Element": "",
        "Sprite": "https://vignette.wikia.nocookie.net/inazuma-eleven/images/7/71/Coach8shot.png",
        "EnglishTeam": "Kirkwood",
        "JapaneseTeam": "Kidokawa Seishuu",
        "TeamSprite": "https://vignette.wikia.nocookie.net/inazuma-eleven/images/f/fe/Kidokawa_Seishuu_sprite.png",
        "Game": "IE1"
    },
    {
        "EnglishName": "David",
        "JapaneseName": "Daisuke",
        "Gender": "Male",
        "Role": "Coach",
        "Position": "",
        "Element": "",
        "Sprite": "https://vignette.wikia.nocookie.net/inazuma-eleven/images/8/84/Daisuke_sprite_0.png",
        "EnglishTeam": "Inazuma Eleven",
        "JapaneseTeam": "Inazuma Eleven",
        "TeamSprite": "https://vignette.wikia.nocookie.net/inazuma-eleven/images/f/f7/Raimon_OB_symbol.png",
        "Game": "IE1"
    },
    {
        "EnglishName": "Sweet",
        "JapaneseName": "Aida",
        "Gender": "Male",
        "Role": "Coach",
        "Position": "",
        "Element": "",
        "Sprite": "https://vignette.wikia.nocookie.net/inazuma-eleven/images/d/db/Aida_Chikara_sprite.png",
        "EnglishTeam": "Inazuma Kids FC",
        "JapaneseTeam": "Inazuma KFC",
        "TeamSprite": "https://vignette.wikia.nocookie.net/inazuma-eleven/images/f/ff/Inazuma_KFC_Logo_Game.png",
        "Game": "IE1"
    },
    {
        "EnglishName": "Loggan",
        "JapaneseName": "Kizaki",
        "Gender": "Male",
        "Role": "Coach",
        "Position": "",
        "Element": "",
        "Sprite": "https://vignette.wikia.nocookie.net/inazuma/images/9/9a/Clint_Loggan.png/revision/latest?cb=20200512093612&path-prefix=es",
        "EnglishTeam": "Umbrella",
        "JapaneseTeam": "Kasamino",
        "TeamSprite": "https://vignette.wikia.nocookie.net/inazuma-eleven/images/a/ab/Kasamino_emblem.png",
        "Game": "IE1"
    }
];